import type { HookExecution } from './hook-command';

export const OMP_EVENT_BY_CLAUDE_HOOK_EVENT = {
  PreToolUse: 'tool_call',
  PostToolUse: 'tool_result',
  SessionStart: 'session_start',
  PreCompact: 'session_before_compact',
  Stop: 'agent_end',
  UserPromptSubmit: 'before_agent_start',
  SubagentStart: 'agent_start',
  SubagentStop: 'agent_end',
} as const;

export type SupportedClaudeHookEvent = keyof typeof OMP_EVENT_BY_CLAUDE_HOOK_EVENT;

export interface ClaudeHookBridgeSpec {
  event: SupportedClaudeHookEvent;
  execution: HookExecution;
  identity: string;
  matcher?: string;
  timeoutSeconds?: number;
}

export function buildClaudeHookBridge(spec: ClaudeHookBridgeSpec): string {
  const ompEvent = OMP_EVENT_BY_CLAUDE_HOOK_EVENT[spec.event];
  const requestedTimeout = spec.timeoutSeconds ?? (spec.event === 'UserPromptSubmit' ? 30 : 600);
  const timeoutSeconds = Number.isFinite(requestedTimeout) && requestedTimeout > 0
    ? requestedTimeout
    : (spec.event === 'UserPromptSubmit' ? 30 : 600);
  const serialized = JSON.stringify({
    claudeEvent: spec.event,
    ompEvent,
    execution: spec.execution,
    identity: spec.identity.replace(/[^a-zA-Z0-9._:/-]/g, '_').slice(0, 160),
    matcher: spec.matcher ?? '',
    timeoutMs: Math.min(timeoutSeconds * 1000, 2_147_483_647),
  });

  return `// AUTO-GENERATED by tdk-setup convert-flat - DO NOT EDIT
import { spawn, execFile, type ChildProcess } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import type { HookAPI } from "@oh-my-pi/pi-coding-agent/extensibility/hooks/types";

type JsonObject = Record<string, unknown>;
type HookArgument = readonly ({ kind: "literal"; value: string } | { kind: "project-root" })[];
type HookExecution = { kind: "node"; script: HookArgument; args: readonly HookArgument[] } | { kind: "posix-shell"; command: string };
type FailureCategory = "spawn-error" | "signal" | "nonzero" | "timeout" | "output-limit" | "unsupported-platform";
type HookRun = { code: number | null; stdout: string; stderr: string; category?: FailureCategory; errno?: string; signal?: string; cleanupFailed?: boolean };
type ParsedHookOutput = { json?: JsonObject; plain?: string; invalid?: boolean };

const SPEC: { claudeEvent: string; ompEvent: string; execution: HookExecution; identity: string; matcher: string; timeoutMs: number } = ${serialized};
const CONSUMER_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");

function objectValue(value: unknown): JsonObject | undefined {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as JsonObject
    : undefined;
}

function stringValue(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function safeSessionValue(context: JsonObject, method: "getSessionId" | "getSessionFile"): string | undefined {
  try {
    const manager = objectValue(context.sessionManager);
    const accessor = manager?.[method];
    if (typeof accessor !== "function") return undefined;
    const value = accessor.call(manager);
    return stringValue(value);
  } catch {
    return undefined;
  }
}

function shouldRunLifecycle(event: JsonObject, context: JsonObject): boolean {
  if (
    SPEC.claudeEvent !== "Stop"
    && SPEC.claudeEvent !== "SubagentStart"
    && SPEC.claudeEvent !== "SubagentStop"
  ) return true;
  if (SPEC.claudeEvent === "Stop" && event.willContinue === true) return false;
  const sessionFile = safeSessionValue(context, "getSessionFile");
  if (!sessionFile) return SPEC.claudeEvent === "Stop";
  const isSubagent = fs.existsSync(\`\${path.dirname(sessionFile)}.jsonl\`);
  return SPEC.claudeEvent === "Stop" ? !isSubagent : isSubagent;
}

function textFromContent(value: unknown): string | undefined {
  if (typeof value === "string") return value;
  if (!Array.isArray(value)) return undefined;
  const text = value
    .map((item) => stringValue(objectValue(item)?.text))
    .filter((item): item is string => item !== undefined)
    .join("\\n");
  return text || undefined;
}

function lastAssistantMessage(event: JsonObject): string | undefined {
  const direct = textFromContent(objectValue(event.message)?.content);
  if (direct) return direct;
  if (!Array.isArray(event.messages)) return undefined;
  for (let index = event.messages.length - 1; index >= 0; index -= 1) {
    const message = objectValue(event.messages[index]);
    if (message?.role === "assistant") return textFromContent(message.content);
  }
  return undefined;
}

function buildEnvelope(event: JsonObject, context: JsonObject): JsonObject {
  const sessionId = safeSessionValue(context, "getSessionId");
  const sessionFile = safeSessionValue(context, "getSessionFile");
  const cwd = stringValue(context.cwd) ?? CONSUMER_ROOT;
  const envelope: JsonObject = {
    ...(sessionId ? { session_id: sessionId } : {}),
    ...(sessionFile ? { transcript_path: sessionFile } : {}),
    cwd,
    hook_event_name: SPEC.claudeEvent,
    event,
    eventName: event.type,
    context: {
      cwd,
      ...(sessionId ? { sessionId } : {}),
      ...(sessionFile ? { sessionFile } : {}),
    },
  };

  if (SPEC.claudeEvent === "PreToolUse" || SPEC.claudeEvent === "PostToolUse") {
    envelope.tool_name = event.toolName;
    envelope.tool_input = objectValue(event.input) ?? {};
    if (stringValue(event.toolCallId)) envelope.tool_use_id = event.toolCallId;
  }
  if (SPEC.claudeEvent === "PostToolUse") {
    envelope.tool_response = {
      content: event.content,
      details: event.details,
      is_error: event.isError === true,
    };
  }
  if (SPEC.claudeEvent === "UserPromptSubmit" && stringValue(event.prompt)) {
    envelope.prompt = event.prompt;
  }
  if (SPEC.claudeEvent === "PreCompact" && stringValue(event.customInstructions)) {
    envelope.custom_instructions = event.customInstructions;
  }
  if (SPEC.claudeEvent === "Stop" || SPEC.claudeEvent === "SubagentStop") {
    envelope.stop_hook_active = false;
    const message = lastAssistantMessage(event);
    if (message) envelope.last_assistant_message = message;
  }
  return envelope;
}

function matches(candidate: unknown): boolean {
  const matcher = SPEC.matcher.trim();
  if (!matcher || matcher === "*") return true;
  if (typeof candidate !== "string" || candidate.length === 0) return true;

  if (/^[a-z0-9_ ,|-]+$/i.test(matcher)) {
    const normalizedCandidate = candidate.toLowerCase();
    return matcher
      .toLowerCase()
      .split(/[|,]/)
      .map((value) => value.trim())
      .filter(Boolean)
      .includes(normalizedCandidate);
  }
  return new RegExp(matcher, "i").test(candidate);
}

function resolveArgument(argument: HookArgument): string {
  return argument.map((part) => part.kind === "project-root" ? CONSUMER_ROOT : part.value).join("");
}

function runHook(payload: JsonObject): Promise<HookRun> {
  const { promise, resolve } = Promise.withResolvers<HookRun>();
  // Serialize before launch: a circular event must not leave an untracked child.
  const input = JSON.stringify(payload);
  if (SPEC.execution.kind === "posix-shell" && process.platform === "win32") {
    resolve({ code: null, stdout: "", stderr: "", category: "unsupported-platform" });
    return promise;
  }
  const command = SPEC.execution.kind === "node" ? "node" : "/bin/sh";
  const args = SPEC.execution.kind === "node"
    ? [resolveArgument(SPEC.execution.script), ...SPEC.execution.args.map(resolveArgument)]
    : ["-c", SPEC.execution.command];
  const stdout: Buffer[] = [];
  const stderr: Buffer[] = [];
  let stdoutBytes = 0;
  let stderrBytes = 0;
  let settled = false;
  let cleaning = false;
  let closed = false;
  let exited = false;
  let code: number | null = null;
  let category: FailureCategory | undefined;
  let errno: string | undefined;
  let signal: string | undefined;
  let cleanupFailed = false;
  let timeoutTimer: NodeJS.Timeout | undefined;
  let escalationTimer: NodeJS.Timeout | undefined;
  let cleanupTimer: NodeJS.Timeout | undefined;
  let child: ChildProcess | undefined;
  let helper: ChildProcess | undefined;

  const settle = (): void => {
    if (settled) return;
    settled = true;
    clearTimeout(timeoutTimer);
    clearTimeout(escalationTimer);
    clearTimeout(cleanupTimer);
    child?.stdin?.destroy();
    child?.stdout?.destroy();
    child?.stderr?.destroy();
    resolve({
      code,
      stdout: category ? "" : Buffer.concat(stdout, stdoutBytes).toString("utf8"),
      stderr: category ? "" : Buffer.concat(stderr, stderrBytes).toString("utf8"),
      category, errno, signal, cleanupFailed,
    });
  };

  const cleanup = (failure: FailureCategory): void => {
    if (settled || cleaning) return;
    cleaning = true;
    category = failure;
    clearTimeout(timeoutTimer);
    const pid = child?.pid;
    if (pid === undefined) { settle(); return; }
    // One finite deadline includes helper startup, graceful termination and escalation.
    cleanupTimer = setTimeout(() => {
      cleanupFailed = true;
      helper?.kill("SIGKILL");
      settle();
    }, 2000);
    if (process.platform === "win32") {
      if (exited) {
        // The numeric root PID no longer establishes ownership. Never retry it.
        cleanupFailed = true;
        settle();
        return;
      }
      // Packaged OMP preflight covers inherited-pipe descendants and parent-first exit.
      // A helper error is never silently treated as proof of termination.
      helper = execFile("taskkill.exe", ["/PID", String(pid), "/T", "/F"], {
        shell: false, timeout: 1500, maxBuffer: 16 * 1024, windowsHide: true,
      }, (error) => {
        if (settled) return;
        cleanupFailed = error !== null;
        settle();
      });
      return;
    }
    // detached:true gives this hook its own process group, not OMP's group.
    try {
      process.kill(-pid, "SIGTERM");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ESRCH") { settle(); return; }
      cleanupFailed = true;
    }
    escalationTimer = setTimeout(() => {
      try {
        process.kill(-pid, "SIGKILL");
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code !== "ESRCH") cleanupFailed = true;
      }
      settle();
    }, 250);
  };

  try {
    child = spawn(command, args, {
      shell: false,
      cwd: CONSUMER_ROOT,
      detached: process.platform !== "win32",
      windowsHide: true,
      stdio: ["pipe", "pipe", "pipe"],
      env: {
        ...process.env,
        CLAUDE_PROJECT_DIR: CONSUMER_ROOT,
        ...(stringValue(payload.session_id) ? { CLAUDE_SESSION_ID: stringValue(payload.session_id) } : {}),
        TDK_HARNESS: "omp",
      },
    });
  } catch (error) {
    category = "spawn-error";
    errno = (error as NodeJS.ErrnoException).code;
    settle();
    return promise;
  }
  child.on("error", (error: NodeJS.ErrnoException) => {
    if (settled || cleaning) return;
    category = "spawn-error";
    errno = error.code;
    settle();
  });
  child.stdout?.on("data", (chunk: Buffer) => {
    if (settled || cleaning) return;
    if (stdoutBytes + chunk.length > 1024 * 1024) { cleanup("output-limit"); return; }
    stdout.push(chunk);
    stdoutBytes += chunk.length;
  });
  child.stderr?.on("data", (chunk: Buffer) => {
    if (settled || cleaning) return;
    if (stderrBytes + chunk.length > 1024 * 1024) { cleanup("output-limit"); return; }
    stderr.push(chunk);
    stderrBytes += chunk.length;
  });
  child.on("exit", (exitCode, exitSignal) => {
    exited = true;
    code = exitCode;
    signal = exitSignal ?? undefined;
  });
  child.on("close", (exitCode, exitSignal) => {
    closed = true;
    if (settled || cleaning) return;
    code = exitCode;
    signal = exitSignal ?? undefined;
    category = signal ? "signal" : code !== 0 && code !== 2 ? "nonzero" : undefined;
    settle();
  });
  timeoutTimer = setTimeout(() => {
    if (!closed) cleanup("timeout");
  }, SPEC.timeoutMs);
  child.stdin?.on("error", () => {
    // Early EPIPE does not establish successful process completion.
  });
  child.stdin?.end(input);
  return promise;
}

function parseOutput(stdout: string): ParsedHookOutput {
  const value = stdout.trim();
  if (!value) return {};
  if (!value.startsWith("{")) return { plain: value };
  try {
    const parsed = JSON.parse(value);
    const json = objectValue(parsed);
    return json ? { json } : { invalid: true };
  } catch {
    return { invalid: true };
  }
}

function hookSpecificOutput(json: JsonObject | undefined): JsonObject | undefined {
  return objectValue(json?.hookSpecificOutput);
}

function additionalContext(output: ParsedHookOutput): string | undefined {
  return stringValue(hookSpecificOutput(output.json)?.additionalContext)
    ?? stringValue(output.json?.additionalContext);
}

function blockingReason(output: ParsedHookOutput, stderr: string): string {
  const specific = hookSpecificOutput(output.json);
  return stringValue(specific?.permissionDecisionReason)
    ?? stringValue(output.json?.reason)
    ?? (stderr.trim() || "Claude hook blocked the operation.");
}

function asTextContent(value: unknown): JsonObject[] {
  const text = typeof value === "string" ? value : JSON.stringify(value);
  return [{ type: "text", text: text ?? "" }];
}

function warn(pi: HookAPI, message: string): void {
  try {
    pi.logger.warn(\`[tdk-setup hook bridge] \${SPEC.identity} \${message}\`.replace(/[\\x00-\\x1f\\x7f]/g, "").slice(0, 512));
  } catch {
    // Logging must never turn a failed bridge into a blocking hook.
  }
}

function translateOutput(pi: HookAPI, event: JsonObject, run: HookRun): unknown {
  if (run.category) {
    const safeErrno = run.errno && ["ENOENT", "EACCES", "EPERM", "EMFILE", "ENFILE", "ENOMEM", "EINVAL"].includes(run.errno) ? run.errno : undefined;
    const safeSignal = run.signal && /^SIG[A-Z0-9]+$/.test(run.signal) ? run.signal : undefined;
    warn(pi, \`event=\${SPEC.claudeEvent}/\${SPEC.ompEvent} category=\${run.category} code=\${run.code} errno=\${safeErrno ?? "-"} signal=\${safeSignal ?? "-"} timeoutMs=\${SPEC.timeoutMs} cleanupFailed=\${run.cleanupFailed === true}\`);
    return undefined;
  }
  const output = parseOutput(run.stdout);
  if (output.invalid) {
    warn(pi, \`event=\${SPEC.claudeEvent}/\${SPEC.ompEvent} category=invalid-json\`);
  }

  if (run.code === 2) {
    if (SPEC.ompEvent === "tool_call") {
      return { block: true, reason: blockingReason(output, run.stderr) };
    }
    if (SPEC.ompEvent === "session_before_compact") return { cancel: true };
    if (SPEC.ompEvent === "tool_result") {
      const feedback = run.stderr.trim();
      return feedback
        ? { content: [...(Array.isArray(event.content) ? event.content : []), ...asTextContent(feedback)] }
        : undefined;
    }
    warn(pi, \`\${SPEC.claudeEvent} exit 2 cannot block OMP event \${SPEC.ompEvent}; continuing\`);
    return undefined;
  }

  if (output.invalid) return undefined;

  const specific = hookSpecificOutput(output.json);
  if (SPEC.ompEvent === "tool_call") {
    const decision = stringValue(specific?.permissionDecision);
    if (decision === "deny" || output.json?.decision === "block") {
      return { block: true, reason: blockingReason(output, run.stderr) };
    }
    const updatedInput = objectValue(specific?.updatedInput);
    if (updatedInput) return { input: updatedInput };
    if (decision || additionalContext(output)) {
      warn(pi, \`\${SPEC.claudeEvent} output has no equivalent OMP control channel; continuing\`);
    }
    return undefined;
  }

  if (SPEC.ompEvent === "tool_result") {
    let content = Array.isArray(event.content) ? [...event.content] : [];
    let changed = false;
    if (specific && Object.prototype.hasOwnProperty.call(specific, "updatedToolOutput")) {
      content = asTextContent(specific.updatedToolOutput);
      changed = true;
    }
    const feedback = additionalContext(output)
      ?? (output.json?.decision === "block" ? stringValue(output.json.reason) : undefined);
    if (feedback) {
      content.push(...asTextContent(feedback));
      changed = true;
    }
    return changed ? { content } : undefined;
  }

  if (SPEC.ompEvent === "session_before_compact") {
    return output.json?.decision === "block" ? { cancel: true } : undefined;
  }

  const context = additionalContext(output) ?? output.plain;
  if (SPEC.ompEvent === "before_agent_start") {
    if (output.json?.decision === "block") {
      warn(pi, "UserPromptSubmit cannot block or rewrite an OMP prompt; continuing");
      return undefined;
    }
    return context ? { message: context } : undefined;
  }
  if ((SPEC.ompEvent === "session_start" || SPEC.ompEvent === "agent_start") && context) {
    pi.sendMessage(context, { triggerTurn: false });
    return undefined;
  }
  if (context || output.json?.decision === "block") {
    warn(pi, \`\${SPEC.claudeEvent} output has no equivalent OMP return channel; continuing\`);
  }
  return undefined;

}

export default function (pi: HookAPI) {
  pi.on(${JSON.stringify(ompEvent)}, async (event, context) => {
    try {
      const rawEvent = event as unknown as JsonObject;
      if (!matches(rawEvent.toolName)) return undefined;
      if (!shouldRunLifecycle(rawEvent, context as unknown as JsonObject)) return undefined;
      const payload = buildEnvelope(rawEvent, context as unknown as JsonObject);
      const run = await runHook(payload);
      return translateOutput(pi, rawEvent, run) as never;
    } catch {
      warn(pi, \`event=\${SPEC.claudeEvent}/\${SPEC.ompEvent} category=bridge-error\`);
      return undefined;
    }
  });
}
`;
}
