import { createHash } from "node:crypto";
import type { CodexCapabilities } from "./codex-capabilities";

interface EventScrubRules {
	deleteFields: string[];
	allowedPermissionValues: string[] | null;
}

function basename(value: string): string {
	return value.split(/[\\/]/).filter(Boolean).pop() ?? "hook.cjs";
}

export function wrapperFilename(originalInvocation: string | string[]): string {
	const invocation = Array.isArray(originalInvocation) ? originalInvocation : [originalInvocation];
	const hash = createHash("sha256").update(JSON.stringify(invocation)).digest("hex").slice(0, 8);
	return `${hash}-${basename(invocation[0] ?? "hook.cjs")}`;
}

export function buildWrapperScript(
	originalInvocation: string | string[],
	capabilities: CodexCapabilities,
	timeoutMs = 30000,
): string {
	const invocationForComment = Array.isArray(originalInvocation)
		? originalInvocation
		: [originalInvocation];
	const invocationExpression = Array.isArray(originalInvocation)
		? JSON.stringify(originalInvocation)
		: `[process.execPath, ${JSON.stringify(originalInvocation)}]`;
	const scrubRules: Record<string, EventScrubRules> = {};
	for (const [event, caps] of Object.entries(capabilities.events)) {
		const deleteFields = caps.supportsAdditionalContext ? [] : ["additionalContext"];
		const allowedPermissionValues = caps.permissionDecisionValues ?? null;
		if (deleteFields.length > 0 || allowedPermissionValues !== null) {
			scrubRules[event] = { deleteFields, allowedPermissionValues };
		}
	}

return `// AUTO-GENERATED by TDK harness-transform - DO NOT EDIT
// Codex hook compatibility wrapper for:
//   ${invocationForComment.join(" ")}
// TDK wraps hook gateway invocations as one original command.

"use strict";

const { spawnSync } = require("node:child_process");

const ORIGINAL_INVOCATION = ${invocationExpression};
const SCRUB_RULES = ${JSON.stringify(scrubRules)};
const HOOK_TIMEOUT_MS = ${timeoutMs};

function getEventFromStdin(stdinData) {
  try {
    const parsed = JSON.parse(stdinData);
    return parsed.hook_event_name || parsed.event || null;
  } catch {
    return null;
  }
}

function sanitizeOutput(obj, rules) {
  if (!obj || typeof obj !== "object" || Array.isArray(obj)) return obj;
  const result = Object.assign({}, obj);
  for (const field of rules.deleteFields) delete result[field];
  if (rules.allowedPermissionValues !== null) {
    const allowed = new Set(rules.allowedPermissionValues);
    if (result.permissionDecision !== undefined && !allowed.has(result.permissionDecision)) {
      delete result.permissionDecision;
    }
    if (result.decision !== undefined && !allowed.has(result.decision)) {
      delete result.decision;
    }
  }
  return result;
}

function eventSupportsDeny(rules) {
  return Boolean(rules && rules.allowedPermissionValues && rules.allowedPermissionValues.includes("deny"));
}

function emitDeny(reason) {
  process.stdout.write(JSON.stringify({
    permissionDecision: "deny",
    reason: reason && reason.length > 0 ? reason : "Hook blocked this operation",
  }));
  process.exit(0);
}

function main() {
  const stdinChunks = [];
  process.stdin.on("data", (chunk) => stdinChunks.push(chunk));
  process.stdin.on("end", () => {
    const stdinData = Buffer.concat(stdinChunks).toString("utf8");
    const event = getEventFromStdin(stdinData);
    const rules = event && SCRUB_RULES[event];
    const result = spawnSync(ORIGINAL_INVOCATION[0], ORIGINAL_INVOCATION.slice(1), {
      input: stdinData,
      env: process.env,
      encoding: "utf8",
      timeout: HOOK_TIMEOUT_MS,
    });

    if (result.error) {
      if (result.stderr) process.stderr.write(result.stderr);
      process.exit(1);
    }

    const stderrText = (result.stderr || "").toString();
    const rawOutput = (result.stdout || "").toString();
    const exitCode = result.status ?? 1;
    const isBlockSignal = exitCode === 2 && eventSupportsDeny(rules);

    if (!rawOutput.trim()) {
      if (isBlockSignal) return emitDeny(stderrText.trim());
      if (stderrText) process.stderr.write(stderrText);
      process.exit(exitCode);
    }

    let parsed;
    try {
      parsed = JSON.parse(rawOutput);
    } catch {
      if (isBlockSignal) return emitDeny(rawOutput.trim() || stderrText.trim());
      if (stderrText) process.stderr.write(stderrText);
      process.stdout.write(rawOutput);
      process.exit(exitCode);
    }

    if (stderrText) process.stderr.write(stderrText);
    const sanitized = rules ? sanitizeOutput(parsed, rules) : parsed;
    if (isBlockSignal && (!sanitized || sanitized.permissionDecision !== "deny")) {
      return emitDeny(stderrText.trim());
    }
    process.stdout.write(JSON.stringify(sanitized));
    process.exit(isBlockSignal ? 0 : exitCode);
  });
}

main();
`;
}
