import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CODEX_CAPABILITY_TABLE } from "../../../src/lib/harness-transform/codex-capabilities";
import { buildWrapperScript, wrapperFilename } from "../../../src/lib/harness-transform/codex-hook-wrapper";

const testDir = join(tmpdir(), "tdk-codex-hook-wrapper-test");
const currentCaps = CODEX_CAPABILITY_TABLE[0];
const legacyCaps =
	CODEX_CAPABILITY_TABLE.find((entry) => entry.version === "0.124.0-alpha.3") ??
	CODEX_CAPABILITY_TABLE[CODEX_CAPABILITY_TABLE.length - 1];

beforeAll(() => {
	mkdirSync(testDir, { recursive: true });
});

afterAll(() => {
	rmSync(testDir, { recursive: true, force: true });
});

describe("codex hook wrapper generation", () => {
	it("generates a no-shebang wrapper with original invocation and timeout", () => {
		const script = buildWrapperScript(["node", "hook-gateway.cjs", "privacy-block"], currentCaps, 45000);
		expect(script.startsWith("#!")).toBe(false);
		expect(script).toContain("AUTO-GENERATED by TDK");
		expect(script).toContain("hook-gateway.cjs");
		expect(script).toContain("HOOK_TIMEOUT_MS = 45000");
	});

	it("uses default 30000ms timeout", () => {
		const script = buildWrapperScript("/hook.cjs", currentCaps);
		expect(script).toContain("HOOK_TIMEOUT_MS = 30000");
	});

	it("bakes scrub rules from capabilities", () => {
		const legacyScript = buildWrapperScript("/hook.cjs", legacyCaps);
		const currentScript = buildWrapperScript("/hook.cjs", currentCaps);
		expect(legacyScript).toContain("additionalContext");
		const rules = JSON.parse(currentScript.match(/const SCRUB_RULES = (\{.*?\});/s)?.[1] ?? "{}");
		expect(rules.PreToolUse.deleteFields).not.toContain("additionalContext");
	});

	it("uses unique hash-prefixed filenames for equal basenames", () => {
		expect(wrapperFilename("/a/privacy-block.cjs")).not.toBe(wrapperFilename("/b/privacy-block.cjs"));
		expect(wrapperFilename("/a/privacy-block.cjs")).toMatch(/^[0-9a-f]{8}-privacy-block\.cjs$/);
	});

	it("uses full gateway invocation for wrapper filename identity", () => {
		expect(wrapperFilename(["node", "/hooks/hook-gateway.cjs", "privacy-block"])).not.toBe(
			wrapperFilename(["node", "/hooks/hook-gateway.cjs", "status-line"]),
		);
	});

	it("translates exit 2 on deny-capable events into Codex deny JSON", () => {
		const original = join(testDir, "block.cjs");
		const wrapper = join(testDir, "wrapper.cjs");
		writeFileSync(
			original,
			'process.stderr.write("Blocked path"); process.exit(2);\n',
		);
		writeFileSync(wrapper, buildWrapperScript([process.execPath, original], currentCaps));

		const result = spawnSync(process.execPath, [wrapper], {
			input: JSON.stringify({ hook_event_name: "PreToolUse" }),
			encoding: "utf8",
		});
		expect(result.status).toBe(0);
		expect(JSON.parse(result.stdout)).toEqual({
			permissionDecision: "deny",
			reason: "Blocked path",
		});
	});

	it("uses raw stdout as deny reason for exit 2 non-JSON output", () => {
		const original = join(testDir, "raw-block.cjs");
		const wrapper = join(testDir, "raw-wrapper.cjs");
		writeFileSync(original, 'process.stdout.write("Denied by raw output"); process.exit(2);\n');
		writeFileSync(wrapper, buildWrapperScript([process.execPath, original], currentCaps));

		const result = spawnSync(process.execPath, [wrapper], {
			input: JSON.stringify({ hook_event_name: "PreToolUse" }),
			encoding: "utf8",
		});
		expect(result.status).toBe(0);
		expect(JSON.parse(result.stdout)).toEqual({
			permissionDecision: "deny",
			reason: "Denied by raw output",
		});
	});

	it("keeps silent exit 0 as silent allow", () => {
		const original = join(testDir, "silent-allow.cjs");
		const wrapper = join(testDir, "silent-wrapper.cjs");
		writeFileSync(original, "process.exit(0);\n");
		writeFileSync(wrapper, buildWrapperScript([process.execPath, original], currentCaps));

		const result = spawnSync(process.execPath, [wrapper], {
			input: JSON.stringify({ hook_event_name: "PreToolUse" }),
			encoding: "utf8",
		});
		expect(result.status).toBe(0);
		expect(result.stdout).toBe("");
	});

	it("preserves JSON deny reason and current additionalContext", () => {
		const original = join(testDir, "json-deny.cjs");
		const wrapper = join(testDir, "json-deny-wrapper.cjs");
		writeFileSync(
			original,
			`process.stdout.write(${JSON.stringify(
				JSON.stringify({
					permissionDecision: "deny",
					reason: "Hook reason",
					additionalContext: "keep me",
				}),
			)}); process.exit(2);\n`,
		);
		writeFileSync(wrapper, buildWrapperScript([process.execPath, original], currentCaps));

		const result = spawnSync(process.execPath, [wrapper], {
			input: JSON.stringify({ hook_event_name: "PreToolUse" }),
			encoding: "utf8",
		});
		expect(result.status).toBe(0);
		expect(JSON.parse(result.stdout)).toEqual({
			permissionDecision: "deny",
			reason: "Hook reason",
			additionalContext: "keep me",
		});
	});

	it("runs a single original CJS path through Node", () => {
		const original = join(testDir, "allow-json.cjs");
		const wrapper = join(testDir, "single-path-wrapper.cjs");
		writeFileSync(original, 'process.stdout.write(JSON.stringify({ok:true}));\n');
		writeFileSync(wrapper, buildWrapperScript(original, currentCaps));

		const result = spawnSync(process.execPath, [wrapper], {
			input: JSON.stringify({ hook_event_name: "PreToolUse" }),
			encoding: "utf8",
		});
		expect(result.status).toBe(0);
		expect(JSON.parse(result.stdout)).toEqual({ ok: true });
	});

	it("passes exit 2 through for events without deny support", () => {
		const original = join(testDir, "stop-block.cjs");
		const wrapper = join(testDir, "stop-wrapper.cjs");
		writeFileSync(original, 'process.stderr.write("Stop blocked"); process.exit(2);\n');
		writeFileSync(wrapper, buildWrapperScript([process.execPath, original], currentCaps));

		const result = spawnSync(process.execPath, [wrapper], {
			input: JSON.stringify({ hook_event_name: "Stop" }),
			encoding: "utf8",
		});
		expect(result.status).toBe(2);
		expect(result.stderr).toContain("Stop blocked");
		expect(result.stdout).toBe("");
		expect(existsSync(wrapper)).toBe(true);
	});
});
