// AUTO-GENERATED by TDK harness-transform - DO NOT EDIT
// Codex hook compatibility wrapper for:
//   /home/vinhuwsl/.bun/bin/bun hooks/hook-gateway.cjs path-rule-injector
// TDK wraps hook gateway invocations as one original command.

"use strict";

const { spawnSync } = require("node:child_process");

const ORIGINAL_INVOCATION = ["/home/vinhuwsl/.bun/bin/bun","hooks/hook-gateway.cjs","path-rule-injector"];
const SCRUB_RULES = {"PreToolUse":{"deleteFields":[],"allowedPermissionValues":["deny","allow","block"]},"PermissionRequest":{"deleteFields":["additionalContext"],"allowedPermissionValues":null},"Stop":{"deleteFields":["additionalContext"],"allowedPermissionValues":null}};
const HOOK_TIMEOUT_MS = 30000;

function getEventFromStdin(stdinData) {
  try {
    const parsed = JSON.parse(stdinData);
    return parsed.hook_event_name || parsed.event || null;
  } catch {
    return null;
  }
}

function sanitizeOutput(obj, rules) {
  if (!obj || typeof obj !== "object" || Array.isArray(obj)) return obj;
  const result = Object.assign({}, obj);
  for (const field of rules.deleteFields) delete result[field];
  if (rules.allowedPermissionValues !== null) {
    const allowed = new Set(rules.allowedPermissionValues);
    if (result.permissionDecision !== undefined && !allowed.has(result.permissionDecision)) {
      delete result.permissionDecision;
    }
    if (result.decision !== undefined && !allowed.has(result.decision)) {
      delete result.decision;
    }
  }
  return result;
}

function eventSupportsDeny(rules) {
  return Boolean(rules && rules.allowedPermissionValues && rules.allowedPermissionValues.includes("deny"));
}

function emitDeny(reason) {
  process.stdout.write(JSON.stringify({
    permissionDecision: "deny",
    reason: reason && reason.length > 0 ? reason : "Hook blocked this operation",
  }));
  process.exit(0);
}

function main() {
  const stdinChunks = [];
  process.stdin.on("data", (chunk) => stdinChunks.push(chunk));
  process.stdin.on("end", () => {
    const stdinData = Buffer.concat(stdinChunks).toString("utf8");
    const event = getEventFromStdin(stdinData);
    const rules = event && SCRUB_RULES[event];
    const result = spawnSync(ORIGINAL_INVOCATION[0], ORIGINAL_INVOCATION.slice(1), {
      input: stdinData,
      env: process.env,
      encoding: "utf8",
      timeout: HOOK_TIMEOUT_MS,
    });

    if (result.error) {
      if (result.stderr) process.stderr.write(result.stderr);
      process.exit(1);
    }

    const stderrText = (result.stderr || "").toString();
    const rawOutput = (result.stdout || "").toString();
    const exitCode = result.status ?? 1;
    const isBlockSignal = exitCode === 2 && eventSupportsDeny(rules);

    if (!rawOutput.trim()) {
      if (isBlockSignal) return emitDeny(stderrText.trim());
      if (stderrText) process.stderr.write(stderrText);
      process.exit(exitCode);
    }

    let parsed;
    try {
      parsed = JSON.parse(rawOutput);
    } catch {
      if (isBlockSignal) return emitDeny(rawOutput.trim() || stderrText.trim());
      if (stderrText) process.stderr.write(stderrText);
      process.stdout.write(rawOutput);
      process.exit(exitCode);
    }

    if (stderrText) process.stderr.write(stderrText);
    const sanitized = rules ? sanitizeOutput(parsed, rules) : parsed;
    if (isBlockSignal && (!sanitized || sanitized.permissionDecision !== "deny")) {
      return emitDeny(stderrText.trim());
    }
    process.stdout.write(JSON.stringify(sanitized));
    process.exit(isBlockSignal ? 0 : exitCode);
  });
}

main();
