import { describe, expect, it } from 'bun:test';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';

// The rename to delegate-routing is a clean break with no fallback, so every reference to the
// former names must be gone. Two categories of reference are deliberate and must survive:
//
//   1. Legacy detection. Warning a consumer that they still hold the old file requires naming
//      that file. Deleting these strings would silently disable the migration warning.
//   2. Migration docs. A `mv <old> <new>` instruction cannot omit the old name.
//
// Obfuscating those strings to satisfy a blanket "zero hits" grep would hide the very sites that
// must stay correct, so this guard pins the exact sanctioned set instead: a missed rename adds a
// file and fails, and deleting a legacy warning removes one and also fails.
//
// Assembled at runtime so this file does not match its own search.
const LEGACY_BASENAME = ['plan', 'skill', 'routing'].join('-');
const LEGACY_PLACEHOLDER = ['DEFAULT', 'SKILL', 'PLACEHOLDER'].join('_');
const LEGACY_TEMPLATE_LEAD = ['Per-project', 'skill', 'mappings'].join(' ');
const LEGACY_COMMAND = ['routing', 'plan-skill'].join(' ');

const REPO_ROOT = resolve(__dirname, '../../../..');

// Historical changelog entries stay as written; manifests are generated by the release tooling.
const EXCLUDED_PATHS = [
  ':!*CHANGELOG.md',
  ':!.specify/plugins/manifest.json',
  ':!.specify/release-manifest.json',
];

// Every file permitted to mention the pre-rename filename, and the reason it must.
const SANCTIONED_LEGACY_REFERENCES: Record<string, string> = {
  '.specify/scripts/ts/src/commands/routing/delegate.ts':
    'existsSync detection that raises the legacy-file warning from `diff`',
  '.specify/scripts/ts/tests/commands/routing/delegate-routing.test.ts':
    'asserts that legacy-file warning fires',
  '.specify/plugins/tdk-core/skills/tdk-implement/references/routing-preflight.md':
    'legacy-detection step that keeps /tdk-implement from losing routing silently',
  '.specify/plugins/tdk-core/skills/tdk-plan/references/delegate-routing-injection.md':
    'legacy-detection step in /tdk-plan file resolution',
  '.specify/docs/en/guides/skills-guide.md': 'migration section `mv` command (EN)',
  '.specify/docs/vi/guides/skills-guide.md': 'migration section `mv` command (VI)',
};

function filesContaining(needle: string): string[] {
  const result = execFileSync('git', ['grep', '-l', '--fixed-strings', needle, '--', '.', ...EXCLUDED_PATHS], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    // git grep exits 1 when nothing matches, which is a valid result here rather than a failure.
    stdio: ['ignore', 'pipe', 'ignore'],
  }).trim();
  return result.length === 0 ? [] : result.split('\n').sort();
}

function filesContainingOrEmpty(needle: string): string[] {
  try {
    return filesContaining(needle);
  } catch {
    return [];
  }
}

describe('delegate-routing legacy reference guard', () => {
  it('mentions the pre-rename filename only where a legacy warning or migration step requires it', () => {
    expect(filesContainingOrEmpty(LEGACY_BASENAME)).toEqual(Object.keys(SANCTIONED_LEGACY_REFERENCES).sort());
  });

  it('retains no pre-rename identifier, template lead line, or CLI command path', () => {
    expect({
      placeholder: filesContainingOrEmpty(LEGACY_PLACEHOLDER),
      templateLead: filesContainingOrEmpty(LEGACY_TEMPLATE_LEAD),
      command: filesContainingOrEmpty(LEGACY_COMMAND),
    }).toEqual({ placeholder: [], templateLead: [], command: [] });
  });
});
